export {default as imgProfile} from "./img/profile.jfif"
export {default as redux} from "./img/Redux_Logo.png"
export {default as Github} from "./img/GitHub.png"
export {default as SQL} from "./img/SQL.png"
export {default as express} from "./img/express.png"
export {default as node} from "./img/node.png"
export {default as react} from "./img/react.png"
export {default as mongoDB} from "./img/mongoDB.png"
// Redes sociales
export {default as github2} from "./img/github2.png"
export {default as linkedin} from "./img/linkedin.png"
export {default as twitter} from "./img/twitter.webp"
export {default as gMail} from "./img/gMail.png"
export {default as lang} from "./img/languagecircle.svg"